version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=Emphasoft
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      SECRET_KEY:  'django-insecure-ey!k-(v*6d8$$3mh*6+$$evypd=5clpi%tgcssd&lz2y+skuml^4'
      DB_PASSWORD: '1234'
    ports:
      - "8000:8000"
    depends_on:
      - db
  lint:
    build: .
    command: bash -c "pip install -r lint-requirements.txt && flake8 --max-line-length 120 --exclude migrations,venv,manage.py"
    volumes:
      - .:/code
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "80:8080"
    volumes:
      - ./doc:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/openapi.yaml
